import re
from dataclasses import dataclass, field

from eth_account import Account
from eth_account.signers.local import LocalAccount

from utils import generate_alias


@dataclass
class Wallet:
    """
    A class representing a cryptocurrency wallet, with functionality for address validation and
    private key management. The class automatically generates an alias and can derive an address
    from a private key when necessary.

    Attributes:
        address (str): The wallet's public address. If not provided, it will be generated from
                       the private key.
        alias (str): A randomly generated alias for the wallet, generated by default using the
                     `generate_alias()` function.
        private_key (str): The private key for the wallet. Used to generate the address if the
                           address is not provided.

    Methods:
        __post_init__(): Validates the provided parameters and, if necessary, generates the wallet's
                         address from the private key.
        _validate_params(address, private_key): Validates that either an address or a private key
                                                is provided, but not both, and checks the format of
                                                the private key.
        generate_address(private_key): Generates an Ethereum address from the private key using
                                        the `Account.from_key` method.
        is_valid_wallet_address(address): Static method that checks if a given address is a valid
                                          Ethereum address (i.e., starts with "0x" and has 42
                                          characters).

    Raises:
        ValueError: If both the address and private key are provided, if neither is provided, or
                    if the address format is invalid.

    Examples:
        >>> wallet = Wallet(private_key="0xabc123...")
        >>> print(wallet.address)
        '0x5aFf...'

        >>> wallet = Wallet(address="0x1234...")
        >>> print(wallet.alias)
        'jxktolpmeh'
    """

    address: str = field(default=None)
    alias: str = field(default_factory=lambda: generate_alias())
    private_key: str = field(default=None)

    def __post_init__(self):
        """
        Post-initialization process for validating inputs and generating the address if only the
        private key is provided. Ensures the integrity of the wallet parameters.
        """
        self._validate_params(self.address, self.private_key)
        if self.private_key:
            self.address = Wallet.generate_address(self.private_key)
        if self.address and not Wallet.is_valid_wallet_address(self.address):
            raise ValueError("Invalid wallet address provided.")

    def _validate_params(self, address, private_key):
        """
        Validates that either the address or private key is provided, but not both.
        Ensures the private key, if given, is properly formatted.

        Args:
            address (str): The wallet's public address, if provided.
            private_key (str): The private key, if provided.

        Raises:
            ValueError: If both or neither of address and private key are provided, or
                        if the private key does not start with '0x'.
        """
        if not (bool(address) ^ bool(private_key)):  # XOR for mutual exclusion
            raise ValueError(
                "You need to specify either an address or a private key, not both."
            )

        # Validate the private key format
        if private_key and not private_key.startswith("0x"):
            raise ValueError("Private key must start with 0x hex prefix")

    @staticmethod
    def generate_address(private_key):
        """
        Generates the Ethereum address from the private key.

        Args:
            private_key (str): The private key used to derive the address.

        Returns:
            str: The generated Ethereum address.
        """
        account: LocalAccount = Account.from_key(private_key)
        return account.address

    @staticmethod
    def is_valid_wallet_address(address):
        """
        Checks if the provided address is a valid Ethereum address, ensuring it starts with '0x'
        and has exactly 42 characters. Validates that the address contains valid hexadecimal characters.

        Args:
            address (str): The wallet's public address.

        Returns:
            bool: True if the address is valid, otherwise False.
        """
        if (
            not isinstance(address, str)
            or not address.startswith("0x")
            or len(address) != 42
        ):
            return False

        hex_pattern = re.compile(r"^0x[a-fA-F0-9]{40}$")
        return bool(hex_pattern.match(address))
